---
title: "Butterworth filtering of Psammomys photopic recordings to extract oscillatory potentials"
author: "Michel Roux"
date: "9/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Retine/Psammomys/ERG") # Indicate here the path to the directory in which the data files are located
```

```{r Loading the required libraries}

library(tidyverse)
library(readxl)
library(ggpubr)
library(gsignal) # butter() and filtfilt() functions
library(gridExtra)
library(xlsx)
```

## Loading data


```{r Importing data from a CSV file exported from the Roland Consult Software}

# The top 17 rows contain metadata that are skipped with the skip = 17 option of read.csv2

fichier ="PSAMLE15WEEKS 4103PHOTOPIC_CATHY ROCHE_20090101_0147_raw"

titres <-c("index", "time", "R1", "L1", "R3", "L3", "R10", "L10", "vide")
erg_data <- read.csv2(paste(fichier,".csv", sep=""), skip = 17, col.names = titres, dec = ".") %>%
  select(c(2:8)) %>% 
  slice_head(n = 512)

# Some of the columns are not considered as containing numbers during the data import, hence a conversion is required

for (i in 1:7) {
  erg_data[i] <- sapply(erg_data[i], as.numeric)
}

# Conversion of the time unit from s to ms, and of the voltage from V to mV
erg_data$time <- erg_data$time * 1000

for (i in 2:7) {
  erg_data[i] <- erg_data[i] * 1000000
}

```

```{r scale and raw graph}

# The script was developed to analyse data obtained from a photopic protocol containing three flash intensities, 1, 3 and 10 Cd.s/m2
# However, the responses to 1 Cd being systematically flat, they are excluded from the analysis and graphical representations.
# In case some recordings include responses to 1 cd, the three next lines should be un-commented, and the following three should be commented.

# min_1Cd <- min(min(erg_data$R1, na.rm = TRUE), min(erg_data$L1, na.rm = TRUE))
# max_1Cd <- max(max(erg_data$R1, na.rm = TRUE), max(erg_data$L1, na.rm = TRUE))
# min_3Cd <- min(min(erg_data$R3, na.rm = TRUE), min(erg_data$L3, na.rm = TRUE))
min_1Cd <- 0
max_1Cd <- 0
min_3Cd <- 0


max_3Cd <- max(max(erg_data$R3, na.rm = TRUE), max(erg_data$L3, na.rm = TRUE))

min_10Cd <- min(min(erg_data$R10, na.rm = TRUE), min(erg_data$L10, na.rm = TRUE))
max_10Cd <- max(max(erg_data$R10, na.rm = TRUE), max(erg_data$L10, na.rm = TRUE))

max_Y <- (max_1Cd + (max_3Cd-min_3Cd) + (max_10Cd- min_10Cd)) * 1.1

# Vertical shift of the traces so they can be drawn on a single graph
# The graph is for visualization only, so the Y axis is kept as is.

erg_data$shifted_R3 <- erg_data$R3  +  (max_1Cd - min_3Cd) * 1.1
erg_data$shifted_R10 <- erg_data$R10 + (max_1Cd - min_3Cd + max_3Cd - min_10Cd) *1.1
erg_data$shifted_L3 <- erg_data$L3  +  (max_1Cd - min_3Cd) * 1.1
erg_data$shifted_L10 <- erg_data$L10 + (max_1Cd - min_3Cd + max_3Cd - min_10Cd) *1.1

# For time shifting the traces from the left eye

erg_data$time_L <- erg_data$time + 300

ggplot(erg_data, aes(x = time)) +
       # geom_line(aes(y = R1), color = "blue", size = 2) +
       geom_line(aes(y = shifted_R3), color = "orange", size = 2) +
       geom_line(aes(y = shifted_R10), color = "grey70", size = 2) +
       # geom_line(aes(x= time_L, y = L1), color = "blue", size = 2) +
       geom_line(aes(x = time_L, y = shifted_L3), color = "orange", size = 2) +
       geom_line(aes(x = time_L, y = shifted_L10), color = "grey70", size = 2) +
    # ylim(-20,max_Y) +
    scale_x_continuous(limits = c(0, 550), breaks = seq(0, 550, 50), labels = c(0,50,100,150,200,250,0,50,100,150,200,250)) + 
    xlab("time (ms)") +
    ylab("amplitude (µV)") + theme_classic()

```

```{r filtering the traces to extract the oscillatory potentials}

# Frequencies in Hz
low = 80
high = 200
acquisition = 2000 # sampling frequency used in the scotopic protocol

# Filtering with the Butterworth method from the gsignal package
# The bandpass interval is set by low.freq* 2/samp.freq and high.freq* 2/samp.freq

bf <- butter(4, c(low*2/acquisition, high*2/acquisition), type = "pass")

# Un-comment these two lines if the 1 Cd traces have to be considered

# erg_data$R1f <- filtfilt(bf, erg_data$R1)
# erg_data$L1f <- filtfilt(bf, erg_data$L1)
erg_data$R3f <- filtfilt(bf, erg_data$R3)
erg_data$L3f <- filtfilt(bf, erg_data$L3)
erg_data$R10f <- filtfilt(bf, erg_data$R10)
erg_data$L10f <- filtfilt(bf, erg_data$L10)

## Un-comment / Comment the next 6 lines lif the 1 Cd traces have to be considered
# min_1f <- min(min(erg_data$R1f, na.rm = TRUE), min(erg_data$L1f, na.rm = TRUE))
# max_1f <- max(max(erg_data$R1f, na.rm = TRUE), max(erg_data$L1f, na.rm = TRUE))
# min_3f<- min(min(erg_data$R3f, na.rm = TRUE), min(erg_data$L3f, na.rm = TRUE))
min_1f <- 0
max_1f <- 0
min_3f <- 0

max_3f <- max(max(erg_data$R3f, na.rm = TRUE), max(erg_data$L3f, na.rm = TRUE))

min_10f <- min(min(erg_data$R10f, na.rm = TRUE), min(erg_data$L10f, na.rm = TRUE))
max_10f <- max(max(erg_data$R10f, na.rm = TRUE), max(erg_data$L10f, na.rm = TRUE))

max_Yf <- (max_1f + (max_3f-min_3f) + (max_10f- min_10f)) * 1.1

# Shifting the filtered traces so that they can be represented without overlap on a single graph
# As in the previous chunk, the graph is for visualization only, so the Y axis is kept as is.

erg_data$shifted_R3f <- erg_data$R3f  +  (max_1f - min_3f) * 1.1
erg_data$shifted_R10f <- erg_data$R10f + (max_1f - min_3f + max_3f - min_10f) *1.1
erg_data$shifted_L3f <- erg_data$L3f  +  (max_1f - min_3f) * 1.1
erg_data$shifted_L10f <- erg_data$L10f + (max_1f - min_3f + max_3f - min_10f) *1.1


write.csv(file = paste(fichier, "_filtered.csv", sep = ""), erg_data)

ggplot(erg_data, aes(x = time)) +
       # geom_line(aes(y = R1f), color = "blue", size = 2) +
       geom_line(aes(y = shifted_R3f), color = "orange", size = 2) +
       geom_line(aes(y = shifted_R10f), color = "grey70", size = 2) +
       # geom_line(aes(x= time_L, y = L1f), color = "blue", size = 2) +
       geom_line(aes(x = time_L, y = shifted_L3f), color = "orange", size = 2) +
       geom_line(aes(x = time_L, y = shifted_L10f), color = "grey70", size = 2) +
    ylim(-20,max_Yf) +
    scale_x_continuous(limits = c(0, 550), breaks = seq(0, 550, 50), labels = c(0,50,100,150,200,250,0,50,100,150,200,250)) + 
    xlab("time (ms)") +
    ylab("amplitude (µV)") + theme_classic()
```


```{r Zoom on Filtered OPs and peak detections}

# representing only the first 100 ms to better see the OPs
erg_data_100 <- erg_data[-c(seq(207,512)),]
erg_data_100$time_L <- erg_data_100$time + 125

peaks_R3 <- findpeaks(erg_data_100$R3f, DoubleSided = TRUE, MinPeakHeight = 0)
R3p <- data.frame(erg_data_100$time[peaks_R3$loc], peaks_R3$pks)
names(R3p) <- c("loc", "pks")
R3p <- R3p[R3p$pks > 0,] # To keep only the positive peaks
rownames(R3p) <- seq(1,nrow(R3p))

peaks_R10 <- findpeaks(erg_data_100$R10f, DoubleSided = TRUE, MinPeakHeight = 0)
R10p <- data.frame(erg_data_100$time[peaks_R10$loc], peaks_R10$pks)
names(R10p) <- c("loc", "pks")
R10p <- R10p[R10p$pks > 0,] # To keep only the positive peaks
rownames(R10p) <- seq(1,nrow(R10p))

peaks_L3 <- findpeaks(erg_data_100$L3f, DoubleSided = TRUE, MinPeakHeight = 0)
L3p <- data.frame(erg_data_100$time[peaks_L3$loc], peaks_L3$pks)
names(L3p) <- c("loc", "pks")
L3p <- L3p[L3p$pks > 0,] # To keep only the positive peaks
rownames(L3p) <- seq(1,nrow(L3p))

peaks_L10 <- findpeaks(erg_data_100$L10f, DoubleSided = TRUE, MinPeakHeight = 0)
L10p <- data.frame(erg_data_100$time[peaks_L10$loc], peaks_L10$pks)
names(L10p) <- c("loc", "pks")
L10p <- L10p[L10p$pks > 0,] # To keep only the positive peaks
rownames(L10p) <- seq(1,nrow(L10p))

ggplot(erg_data_100, aes(x = time)) +
      # geom_line(aes(y = R1f), color = "blue", size = 2) +
      geom_line(aes(y = shifted_R3f), color = "orange", size = 2) +
      geom_line(aes(y = shifted_R10f), color = "grey70", size = 2) +
      geom_point(data = R3p, aes(x= loc, y = pks), color = "red", size = 3) +
      geom_point(data = R10p, aes(x= loc, y = pks + (max_3f - min_10f) *1.1), color = "red", size = 3) +
      # geom_line(aes(x= time_L, y = L1f), color = "blue", size = 2) +
      geom_line(aes(x = time_L, y = shifted_L3f), color = "orange", size = 2) +
      geom_line(aes(x = time_L, y = shifted_L10f), color = "grey70", size = 2) +
      geom_point(data = L3p, aes(x= loc + 125, y = pks), color = "red", size = 3) +
      geom_point(data = L10p, aes(x= loc + 125 , y = pks + (max_3f - min_10f) *1.1), color = "red", size = 3) +
    # ylim(-25,max_Yf) +
    scale_x_continuous(limits = c(0, 225), breaks = seq(0, 225, 25), labels = c(0,25,50,75,100,0,25,50,75,100)) + 
    xlab("time (ms)") +
    ylab("amplitude (µV)") + theme_classic()
```
```{r Determining the OPs and graphical representation, fig.width = 13, fig.height = 7}

# Initializing  the data frames that will contain the parameters of the 4 OPs for each trace.
R3f <- c(0,0,0,0)
L3f <- c(0,0,0,0)
R10f <- c(0,0,0,0)
L10f <- c(0,0,0,0)

i_OP <- data.frame(R3f, L3f, R10f, L10f)
A_OP <- data.frame(R3f, L3f, R10f, L10f)
t_OP <- data.frame(R3f, L3f, R10f, L10f)

# Defining the time intervals in which each OP should be looked for : 
# OP1 between 7.8 and 23 ms =  points 17 and 48
# OP2 between 23 and 33.8 ms = points 48 and 70
# OP3 between 33.8 and 44 ms = points 70 and 91
# OP4 between 44 and 56.3 ms = points 91 and 116

intervalle_min <- c(17, 48, 70, 91)
intervalle_max <- c(48,70, 91, 116)

for (enregistrement in c("R3f", "L3f", "R10f", "L10f")) { 
  for (op in 1:4) {
    for (i in intervalle_min[op]:intervalle_max[op]) {
      if (erg_data_100[i, enregistrement] > A_OP[op, enregistrement]) {
        i_OP[op, enregistrement] <- i
        t_OP[op, enregistrement] <- erg_data_100$time[i]
        A_OP[op, enregistrement] <- erg_data_100[i, enregistrement]
      }
    }
  }
}

# Saving the results in Excel format

write.xlsx(t_OP, file=paste(fichier, "_OPs.xlsx", sep = ""), sheetName = "Time")
write.xlsx(A_OP, file=paste(fichier, "_OPs.xlsx", sep = ""), sheetName = "Amplitude", append = TRUE)

# Regrouping the peak coordinates (found with the findpeaks() function) in a single data frame and saving them in Excel format
max_pics <- max(nrow(R3p), nrow(L3p), nrow(R10p), nrow(L10p))
pics <- data.frame( c(R3p$loc ,rep(NA, max_pics - nrow(R3p))), c(R3p$pks,rep(NA, max_pics - nrow(R3p))),
                    c(L3p$loc ,rep(NA, max_pics - nrow(L3p))), c(L3p$pks,rep(NA, max_pics - nrow(L3p))),
                    c(R10p$loc ,rep(NA, max_pics - nrow(R10p))), c(R10p$pks,rep(NA, max_pics - nrow(R10p))),
                    c(L10p$loc ,rep(NA, max_pics - nrow(L10p))), c(L10p$pks,rep(NA, max_pics - nrow(L10p))) )
names(pics) <- c("R3_t (ms)", "R3_A (µV)", "L3_t (ms)", "L3_A (µV)", "R10_t (ms)", "R10_A (µV)", "L10_t (ms)", "L10_A (µV)")

write.xlsx(pics, file=paste(fichier, "_OPs.xlsx", sep = ""), sheetName = "Pics", append = TRUE, row.names = FALSE, showNA = FALSE)


# Plotting the OP zone for each traces, with each detected peak marked with a numbered red dot
# The four search regions are shaded in grey, and the peak considered as the OP in each region is indicated
# with a vertical doted red lines
# If some of those automatcally detected peaks are considered as not placed correctly,
# the numbered red dots can be used to access the coordinates of the peak considered by the experimenter as correct.

OP3L <- ggplot(erg_data_100, aes(x = time)) +
  ggtitle(expression('Left: 3 Cd.s.m'^-2)) +
  geom_rect(xmin = erg_data_100$time[intervalle_min[1]], xmax = erg_data_100$time[intervalle_max[1]], ymin = -Inf, ymax = Inf, fill = "grey90", alpha = 0.2) +
  geom_rect(xmin = erg_data_100$time[intervalle_min[2]], xmax = erg_data_100$time[intervalle_max[2]], ymin = -Inf, ymax = Inf, fill = "grey80", alpha = 0.2) +
  geom_rect(xmin = erg_data_100$time[intervalle_min[3]], xmax = erg_data_100$time[intervalle_max[3]], ymin = -Inf, ymax = Inf, fill = "grey90", alpha = 0.2) +
  geom_rect(xmin = erg_data_100$time[intervalle_min[4]], xmax = erg_data_100$time[intervalle_max[4]], ymin = -Inf, ymax = Inf, fill = "grey80", alpha = 0.2) +
  geom_line(aes(y = L3f), color = "blue", size = 2) +
  geom_vline(xintercept = t_OP[1, "L3f"], color = "red", size = 1, linetype = "dashed") +
  geom_vline(xintercept = t_OP[2, "L3f"], color = "red", size = 1, linetype = "dashed") +
  geom_vline(xintercept = t_OP[3, "L3f"], color = "red", size = 1, linetype = "dashed") +
  geom_vline(xintercept = t_OP[4, "L3f"], color = "red", size = 1, linetype = "dashed") +
  geom_hline(yintercept = 0, color = "black", size = 1, linetype = "dotted") +
  geom_point(data = L3p, aes(x= loc, y = pks), color = "red", size = 3) +
  geom_text(data = L3p, aes(x= loc, y = pks, label = rownames(L3p)), color = "red", nudge_x = 2, nudge_y =0.8) +
  xlab("time (ms)") +
  ylab("amplitude (µV)") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 1))

OP3R <- ggplot(erg_data_100, aes(x = time)) +
  ggtitle(expression('Right: 3 Cd.s.m'^-2)) +
  geom_rect(xmin = erg_data_100$time[intervalle_min[1]], xmax = erg_data_100$time[intervalle_max[1]], ymin = -Inf, ymax = Inf, fill = "grey90", alpha = 0.2) +
  geom_rect(xmin = erg_data_100$time[intervalle_min[2]], xmax = erg_data_100$time[intervalle_max[2]], ymin = -Inf, ymax = Inf, fill = "grey80", alpha = 0.2) +
  geom_rect(xmin = erg_data_100$time[intervalle_min[3]], xmax = erg_data_100$time[intervalle_max[3]], ymin = -Inf, ymax = Inf, fill = "grey90", alpha = 0.2) +
  geom_rect(xmin = erg_data_100$time[intervalle_min[4]], xmax = erg_data_100$time[intervalle_max[4]], ymin = -Inf, ymax = Inf, fill = "grey80", alpha = 0.2) +
  geom_line(aes(y = R3f), color = "blue", size = 2) +
  geom_vline(xintercept = t_OP[1, "R3f"], color = "red", size = 1, linetype = "dashed") +
  geom_vline(xintercept = t_OP[2, "R3f"], color = "red", size = 1, linetype = "dashed") +
  geom_vline(xintercept = t_OP[3, "R3f"], color = "red", size = 1, linetype = "dashed") +
  geom_vline(xintercept = t_OP[4, "R3f"], color = "red", size = 1, linetype = "dashed") +
  geom_hline(yintercept = 0, color = "black", size = 1, linetype = "dotted") +
  geom_point(data = R3p, aes(x= loc, y = pks), color = "red", size = 3) +
  geom_text(data = R3p, aes(x= loc, y = pks, label = rownames(R3p)), color = "red", nudge_x = 2, nudge_y =0.8) +
  xlab("time (ms)") +
  ylab("amplitude (µV)") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 1))

OP10L <- ggplot(erg_data_100, aes(x = time)) +
  ggtitle(expression('Left: 10 Cd.s.m'^-2)) +
  geom_rect(xmin = erg_data_100$time[intervalle_min[1]], xmax = erg_data_100$time[intervalle_max[1]], ymin = -Inf, ymax = Inf, fill = "grey90", alpha = 0.2) +
  geom_rect(xmin = erg_data_100$time[intervalle_min[2]], xmax = erg_data_100$time[intervalle_max[2]], ymin = -Inf, ymax = Inf, fill = "grey80", alpha = 0.2) +
  geom_rect(xmin = erg_data_100$time[intervalle_min[3]], xmax = erg_data_100$time[intervalle_max[3]], ymin = -Inf, ymax = Inf, fill = "grey90", alpha = 0.2) +
  geom_rect(xmin = erg_data_100$time[intervalle_min[4]], xmax = erg_data_100$time[intervalle_max[4]], ymin = -Inf, ymax = Inf, fill = "grey80", alpha = 0.2) +
  geom_line(aes(y = L10f), color = "blue", size = 2) +
  geom_vline(xintercept = t_OP[1, "L10f"], color = "red", size = 1, linetype = "dashed") +
  geom_vline(xintercept = t_OP[2, "L10f"], color = "red", size = 1, linetype = "dashed") +
  geom_vline(xintercept = t_OP[3, "L10f"], color = "red", size = 1, linetype = "dashed") +
  geom_vline(xintercept = t_OP[4, "L10f"], color = "red", size = 1, linetype = "dashed") +
  geom_point(data = L10p, aes(x= loc, y = pks), color = "red", size = 3) +
  geom_text(data = L10p, aes(x= loc, y = pks, label = rownames(L10p)), color = "red", nudge_x = 2, nudge_y =0.8) +
  xlab("time (ms)") +
  ylab("amplitude (µV)") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 1))

OP10R <- ggplot(erg_data_100, aes(x = time)) +
  ggtitle(expression('Right: 10 Cd.s.m'^-2)) +
  geom_rect(xmin = erg_data_100$time[intervalle_min[1]], xmax = erg_data_100$time[intervalle_max[1]], ymin = -Inf, ymax = Inf, fill = "grey90", alpha = 0.2) +
  geom_rect(xmin = erg_data_100$time[intervalle_min[2]], xmax = erg_data_100$time[intervalle_max[2]], ymin = -Inf, ymax = Inf, fill = "grey80", alpha = 0.2) +
  geom_rect(xmin = erg_data_100$time[intervalle_min[3]], xmax = erg_data_100$time[intervalle_max[3]], ymin = -Inf, ymax = Inf, fill = "grey90", alpha = 0.2) +
  geom_rect(xmin = erg_data_100$time[intervalle_min[4]], xmax = erg_data_100$time[intervalle_max[4]], ymin = -Inf, ymax = Inf, fill = "grey80", alpha = 0.2) +
  geom_line(aes(y = R10f), color = "blue", size = 2) +
  geom_vline(xintercept = t_OP[1, "R10f"], color = "red", size = 1, linetype = "dashed") +
  geom_vline(xintercept = t_OP[2, "R10f"], color = "red", size = 1, linetype = "dashed") +
  geom_vline(xintercept = t_OP[3, "R10f"], color = "red", size = 1, linetype = "dashed") +
  geom_vline(xintercept = t_OP[4, "R10f"], color = "red", size = 1, linetype = "dashed") +
  geom_point(data = R10p, aes(x= loc, y = pks), color = "red", size = 3) +
  geom_text(data = R10p, aes(x= loc, y = pks, label = rownames(R10p)), color = "red", nudge_x = 2, nudge_y =0.8) +
  xlab("time (ms)") +
  ylab("amplitude (µV)") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 1))

graphe <- arrangeGrob(OP3L, OP3R, OP10L, OP10R, ncol = 2) 

plot(graphe)

```

