---
title: "Filtration of Psammomys photopic recordings"
author: "Michel Roux"
date: "9/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/R_work/ERG") # Indicate here the path to the directory in which the data files are located
```

```{r Chargement des librairies}

library(tidyverse)
library(readxl)
library(ggpubr)
library(gsignal) # butter() and filtfilt() functions
library(gridExtra)
library(xlsx)
```

## Loading data

```{r Importing data from a CSV file exported from the Roland Consult Software}

# The top 17 rows contain metadata that are skipped with the skip = 17 option of read.csv2

fichier <- "sample_scotopic_recording"

titres <-c("indice", "time", "R1", "L1", "R3", "L3", "R10", "L10", "vide")
erg_data <- read.csv2(paste(fichier,".csv", sep=""), skip = 17, col.names = titres, dec = ".") %>% 
  select(c(2:8)) %>% 
  slice_head(n = 512) 
  
# The script was developed to analyse data obtained from a scotopic protocol containing three flash intensities, 1, 3 and 10 Cd.s/m2
# For an unknown reason, all the files provided to me for analysis contained flat responses to 1 and 3 Cd flashes, so they are removed from the data frame :

erg_data <- erg_data[-c(2,3,4,5)]

# Some of the columns are not considered as containing numbers during the data import, hence a conversion is required
for (i in 1:3) {
  erg_data[i] <- sapply(erg_data[i], as.numeric)
}

# time and voltage are in s and V respectively, let's transform them in ms and µV
erg_data$time <- erg_data$time * 1000

for (i in 2:3) {
  erg_data[i] <- erg_data[i] * 1000000
}

```

```{r scale and raw graph}

   
min_10Cd <- min(min(erg_data$R10, na.rm = TRUE), min(erg_data$L10, na.rm = TRUE))
max_10Cd <- max(max(erg_data$R10, na.rm = TRUE), max(erg_data$L10, na.rm = TRUE))

# For time shifting the traces from the left eye

erg_data$time_L <- erg_data$time + 450

ggplot(erg_data, aes(x = time)) +
    geom_line(aes(y = R10), color = "grey70", size = 2) +
    geom_line(aes(x = time_L, y = L10), color = "grey70", size = 2) +
    scale_x_continuous(limits = c(0, 950), breaks = seq(0, 850, 50), labels = c(0,"",100,"",200,"",300,"",400,0,"",100,"",200,"",300,"",400)) + 
    xlab("time (ms)") +
    ylab("amplitude (µV)") + theme_classic()

```


```{r filtering the traces to extract the oscillatory potentials}

# Frequencies in Hz
low = 80
high = 200
acquisition = 1280 # sampling frequency used in the scotopic protocol

# Filtering with the Butterworth method from the gsignal package
# The bandpass interval is set by low.freq* 2/samp.freq and high.freq* 2/samp.freq

bf <- butter(4, c(low*2/acquisition, high*2/acquisition), type = "pass")

erg_data$R10f <- filtfilt(bf, erg_data$R10)
erg_data$L10f <- filtfilt(bf, erg_data$L10)

write.csv(file = paste(fichier, "_filtered.csv", sep = ""), erg_data)

ggplot(erg_data, aes(x = time)) +
    geom_line(aes(y = R10f), color = "grey70", size = 2) +
    geom_line(aes(x = time_L, y = L10f), color = "grey70", size = 2) +
    scale_x_continuous(limits = c(0, 950), breaks = seq(0, 850, 50), labels = c(0,"",100,"",200,"",300,"",400,0,"",100,"",200,"",300,"",400)) + 
    xlab("time (ms)") +
    ylab("amplitude (µV)") + theme_classic()
```


```{r Zoom on Filtered OPs and peak detections}
# Representing only the first 100 ms to better see the OPs
erg_data_100 <- erg_data[-c(seq(130,512)),]
erg_data_100$time_L <- erg_data_100$time + 125

peaks_R10 <- findpeaks(erg_data_100$R10f, DoubleSided = TRUE, MinPeakHeight = 0)
R10p <- data.frame(erg_data_100$time[peaks_R10$loc], peaks_R10$pks)
names(R10p) <- c("loc", "pks")
R10p <- R10p[R10p$pks > 0,] # To keep only the positive peaks
rownames(R10p) <- seq(1,nrow(R10p))

peaks_L10 <- findpeaks(erg_data_100$L10f, DoubleSided = TRUE, MinPeakHeight = 0)
L10p <- data.frame(erg_data_100$time[peaks_L10$loc], peaks_L10$pks)
names(L10p) <- c("loc", "pks")
L10p <- L10p[L10p$pks > 0,] # To keep only the positive peaks
rownames(L10p) <- seq(1,nrow(L10p))

ggplot(erg_data_100, aes(x = time)) +
    geom_line(aes(y = R10f), color = "grey70", size = 2) +
    geom_line(aes(x = time_L, y = L10f), color = "grey70", size = 2) +
    scale_x_continuous(limits = c(0, 225), breaks = seq(0, 225, 25), labels = c(0,25,50,75,100,0,25,50,75,100)) + 
    xlab("time (ms)") +
    ylab("amplitude (µV)") + theme_classic()
```

```{r Determining the OPs and graphical representation, fig.width = 13, fig.height = 7}

# Initialisation des valeurs pour amplitude et temps des quatre OPs


# Defining the time intervals in which each OP should be looked for : 
# OP1 between 12.5 and 23.5 ms =  points 17 and 31
# OP2 between 23.5 and 31.3 ms = points 31 and 41
# OP3 between 31.3 and 40.7 ms = points 41 and 53
# OP4 between 40.7 and 50 ms = points 59 and 65
intervalle_min <- c(17, 31, 41, 53)
intervalle_max <- c(31, 41, 53, 65)


R10f <- c(0,0,0,0)
L10f <- c(0,0,0,0)
i_OP <- data.frame(R10f, L10f)
t_OP <- data.frame(R10f, L10f)
A_OP <- data.frame(R10f, L10f)


for (enregistrement in c("R10f", "L10f")) { 
  for (op in 1:4) {
    for (i in intervalle_min[op]:intervalle_max[op]) {
      if ( (erg_data_100[i, enregistrement] > erg_data_100[i+1, enregistrement]) &&  (erg_data_100[i, enregistrement] > erg_data_100[i-1, enregistrement])) {
        if ( is.na(A_OP[op, enregistrement]) || (erg_data_100[i, enregistrement] > A_OP[op, enregistrement])) {
          i_OP[op, enregistrement] <- i
          t_OP[op, enregistrement] <- erg_data_100$time[i]
          A_OP[op, enregistrement] <- erg_data_100[i, enregistrement]
        }
      }
    }
  }
}
# Saving the results in Excel format

write.xlsx(t_OP, file=paste(fichier, "_OPs.xlsx", sep = ""), sheetName = "Time")
write.xlsx(A_OP, file=paste(fichier, "_OPs.xlsx", sep = ""), sheetName = "Amplitude", append = TRUE)

# Regrouping the peak coordinates (found with the findpeaks() function) in a single data frame and saving them in Excel format
max_pics <- max(nrow(R10p), nrow(L10p))
pics <- data.frame( c(R10p$loc ,rep(NA, max_pics - nrow(R10p))), c(R10p$pks,rep(NA, max_pics - nrow(R10p))),
                    c(L10p$loc ,rep(NA, max_pics - nrow(L10p))), c(L10p$pks,rep(NA, max_pics - nrow(L10p))) )
names(pics) <- c("R10_t (ms)", "R10_A (µV)", "L10_t (ms)", "L10_A (µV)")

write.xlsx(pics, file=paste(fichier, "_OPs.xlsx", sep = ""), sheetName = "Pics", append = TRUE, row.names = FALSE, showNA = FALSE)

# Plotting the OP zone for each traces, with each detected peak marked with a numbered red dot
# The four search regions are shaded in grey, and the peak considered as the OP in each region is indicated
# with a vertical doted red lines
# If some of those automatcally detected peaks are considered as not placed correctly,
# the numbered red dots can be used to access the coordinates of the peak considered by the experimenter as correct.

OP10L <- ggplot(erg_data_100, aes(x = time)) +
  ggtitle(expression('Left: 10 Cd.s.m'^-2)) +
  geom_rect(xmin = erg_data_100$time[intervalle_min[1]], xmax = erg_data_100$time[intervalle_max[1]],
            ymin = -Inf, ymax = Inf, fill = "grey90", alpha = 0.2) +
  geom_rect(xmin = erg_data_100$time[intervalle_min[2]], xmax = erg_data_100$time[intervalle_max[2]],
            ymin = -Inf, ymax = Inf, fill = "grey80", alpha = 0.2) +
  geom_rect(xmin = erg_data_100$time[intervalle_min[3]], xmax = erg_data_100$time[intervalle_max[3]],
            ymin = -Inf, ymax = Inf, fill = "grey90", alpha = 0.2) +
  geom_rect(xmin = erg_data_100$time[intervalle_min[4]], xmax = erg_data_100$time[intervalle_max[4]],
            ymin = -Inf, ymax = Inf, fill = "grey80", alpha = 0.2) +
  geom_line(aes(y = L10f), color = "blue", size = 2) +
  geom_point(data = L10p, aes(x= loc, y = pks), color = "red", size = 3) +
  geom_text(data = L10p, aes(x= loc, y = pks, label = rownames(L10p)), color = "red", nudge_x = 2, nudge_y =0.8) +
  geom_vline(xintercept = t_OP[1, "L10f"], color = "red", size = 1, linetype = "dashed") +
  geom_vline(xintercept = t_OP[2, "L10f"], color = "red", size = 1, linetype = "dashed") +
  geom_vline(xintercept = t_OP[3, "L10f"], color = "red", size = 1, linetype = "dashed") +
  geom_vline(xintercept = t_OP[4, "L10f"], color = "red", size = 1, linetype = "dashed") +
  xlab("time (ms)") +
  ylab("amplitude (µV)") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 1))


OP10R <- ggplot(erg_data_100, aes(x = time)) +
  ggtitle(expression('Right: 10 Cd.s.m'^-2)) +
  geom_rect(xmin = erg_data_100$time[intervalle_min[1]], xmax = erg_data_100$time[intervalle_max[1]],
            ymin = -Inf, ymax = Inf, fill = "grey90", alpha = 0.1) +
  geom_rect(xmin = erg_data_100$time[intervalle_min[2]], xmax = erg_data_100$time[intervalle_max[2]],
            ymin = -Inf, ymax = Inf, fill = "grey80", alpha = 0.1) +
  geom_rect(xmin = erg_data_100$time[intervalle_min[3]], xmax = erg_data_100$time[intervalle_max[3]],
            ymin = -Inf, ymax = Inf, fill = "grey90", alpha = 0.1) +
  geom_rect(xmin = erg_data_100$time[intervalle_min[4]], xmax = erg_data_100$time[intervalle_max[4]],
            ymin = -Inf, ymax = Inf, fill = "grey80", alpha = 0.1) +
  geom_line(aes(y = R10f), color = "blue", size = 2) +
  geom_point(data = R10p, aes(x= loc, y = pks), color = "red", size = 3) +
  geom_text(data = R10p, aes(x= loc, y = pks, label = rownames(R10p)), color = "red", nudge_x = 2, nudge_y =0.8) +
  geom_vline(xintercept = t_OP[1, "R10f"], color = "red", size = 1, linetype = "dashed") +
  geom_vline(xintercept = t_OP[2, "R10f"], color = "red", size = 1, linetype = "dashed") +
  geom_vline(xintercept = t_OP[3, "R10f"], color = "red", size = 1, linetype = "dashed") +
  geom_vline(xintercept = t_OP[4, "R10f"], color = "red", size = 1, linetype = "dashed") +
  xlab("time (ms)") +
  ylab("amplitude (µV)") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 1))

graphe <- arrangeGrob(OP10L, OP10R, ncol = 2) 

plot(graphe)

```
